version: "3.3"

services:

    db:
        image: postgres:12.8-alpine
        restart: always
        # env_file: # - .env

        environment:
            POSTGRES_USER: "{DB_USER}"
            POSTGRES_PASSWORD: "{DB_PASSWORD}"
            POSTGRES_DB: "{DB_NAME}"
        ports:
            - 5432:5432

   

    app:
        # env_file: # - .env
        build:
            context: .
            dockerfile: ./Dockerfile
        command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
        
        ports:
            - 8000:8000
            # depends_on:
            #   - db
            
        volumes:
            - .:/app
        environment:
            PYTHONPATH: /app
       
        stdin_open: true
        tty: true

    celery-worker:
        # env_file:
        #   - .env
        build:
            context: .
            dockerfile: ./Dockerfile
        command: celery -A budgeteer worker --loglevel=INFO 
        depends_on:
            - app
        volumes:
            - .:/app
