# Generated by Django 4.1.2 on 2022-11-03 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_monthlyincome"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="income",
            field=models.IntegerField(default=0),
        ),
    ]
