# Generated by Django 4.1.2 on 2022-11-03 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_customuser_income"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="income",
            new_name="amount",
        ),
    ]
