# Generated by Django 4.1.2 on 2022-11-04 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_rename_income_customuser_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="weeklycategory",
            name="amount",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="weeklyexpense",
            name="amount",
            field=models.IntegerField(default=0),
        ),
    ]
