# Generated by Django 4.1.3 on 2022-12-23 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_monthlyincome_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyincome',
            name='account_balance',
            field=models.IntegerField(default=0),
        ),
    ]
